name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build (${{ matrix.platform }})

    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - platform: Interp
            dependencies: 
            build_postfix: --interp

          - platform: C++
            dependencies: haxelib git hxcpp https://github.com/ALE-Psych-Crew/hxcpp
            build_postfix: --cpp bin --cmd ./bin/Main

          - platform: Hashlink
            dependencies: 
            build_postfix: --hl bin\bin.hl -cmd "hl bin\bin.hl"

          - platform: Lua
            dependencies: haxelib install hxluajit
            build_postfix: --lua bin/bin.lua

          - platform: JavaScript
            dependencies: 
            build_postfix: --js bin/bin.js

    steps:
      - uses: actions/checkout@v4

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.7

      - name: Setup HashLink
        if: matrix.platform == 'Hashlink'
        uses: cedx/SetupHashLink@v8
        with:
          version: latest

      - name: Install Dependencies
        run: |
          haxelib dev ale-hscript .
          ${{ matrix.dependencies }}

      - name: Build
        run: |
          cd tests
          haxe build.hxml -D VERBOSE_TEST ${{ matrix.build_postfix }}